# Server
quarkus.http.port=8080

# Database (PostgreSQL Example)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ecommerce
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.hibernate-orm.database.generation=update

# Hibernate show SQL (optional)
quarkus.hibernate-orm.log.sql=true

# JWT Auth
mp.jwt.verify.issuer=ecommerce-app
mp.jwt.verify.publickey.location=META-INF/publicKey.pem

# Dev mode hot reload
quarkus.live-reload.password=dev